version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: hustlehub-mango_web_1
      APP_PORT: 341341
  web:
    image: hkalexling/mango:latest
    restart: on-failure
    stop_grace_period: 1m
    ports:
      - "341341:341341"
    volumes:
      - ${APP_DATA_DIR}:/root/mango
      - ${APP_DATA_DIR}:/root/.config/mango