version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: hustlehub-stump-app_server_1
      APP_PORT: 49152
  web:
    image: aaronleopold/stump:nightly
    restart: on-failure
    stop_grace_period: 1m
    ports:
      - 49152:49152
    volumes:
      - ${APP_DATA_DIR}:/data
      - ${APP_DATA_DIR}:/config